---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# TWB2R

<!-- badges: start -->
<!-- badges: end -->

The goal of TWB2R is to ...

## Installation

You can install the development version of TWB2R from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("KirstinLyon/TWB2R")
```


## Import Library
```{r import}
library(TWB2R)
library(tidyverse)
library(xml2)
```


## Example

Read in a Tableau workbook as XML and view metadata.

```{r example}
#Read in tableau twb files  (NB:  unpackage a twbx file to get a twb)
twb_file <- read_xml("inst/extdata/Data/tableau_example_workbook.twb")

#Extract the meta-data for fields using TWB2R
all_datasources <- TWB2R::all_datasources(twb_file) #All datasources connected to the workbook
all_windows <- TWB2R::all_windows(twb_file) #all worksheets, dashboards and storyboards in the workbook
Raw <- TWB2R::all_raw_fields(twb_file) #all fields from the datasets
calcs <- TWB2R::all_other_created(twb_file) #all calculations created in the workbook
param <- TWB2R::all_parameters(twb_file) #all parameters created in the workbook

```


